trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  servicePrincipalId: $(servicePrincipalId)
  servicePrincipalKey: $(servicePrincipalKey)
  tenantId: $(tenantId)
  subscriptionId: $(subscriptionId)

stages:
  - stage: Terraform
    jobs:
      - job: TerraformPlan
        steps:
          - task: AzureCLI@2
            displayName: 'Authenticate using Azure service connection'
            inputs:
              azureSubscription: 'azure-sc'  # Replace with your service connection name
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Running Terraform init"
                rm -rf .terraform
                terraform init
                echo "Running Terraform plan"
                terraform plan
          
          - task: Bash@3
            displayName: 'Run Terraform Plan'
            inputs:
              targetType: 'inline'
              script: |
                terraform plan









