trigger:
  - main

variables:
  - group: azure_credential  # Ensures variable group is linked

stages:
  - stage: Terraform_Deployment
    displayName: "Terraform Deployment"
    jobs:
      - job: Terraform
        displayName: "Run Terraform"
        pool:
          vmImage: "ubuntu-latest"

        steps:
          # Authenticate using Azure Service Connection
          - task: AzureCLI@2
            displayName: "Azure Authentication"
            inputs:
              azureSubscription: "azure-sc"  
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az account show

          # Install Terraform
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: "latest"

          # Terraform Init - **Local Backend (No Storage Account)**
          - script: |
              terraform init
            displayName: "Terraform Init"
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)

          # Terraform Plan
          - script: |
              terraform plan -out=tfplan -input=false
            displayName: "Terraform Plan"
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)

          # Terraform Apply
          - script: |
              terraform apply -auto-approve tfplan
            displayName: "Terraform Apply"
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)

























