trigger:
- main  # Runs pipeline when main.tf is changed in GitHub

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: azure_credential  # Using your Variable Group

steps:
- checkout: self

- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'

- script: |
    terraform init
  displayName: 'Terraform Init'

- script: |
    terraform plan -out=tfplan -input=false \
      -var "CLIENT_ID=$(CLIENT_ID)" \
      -var "CLIENT_SECRET=$(CLIENT_SECRET)" \
      -var "SUBSCRIPTION_ID=$(SUBSCRIPTION_ID)" \
      -var "TENANT_ID=$(TENANT_ID)"
  displayName: 'Terraform Plan'

- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'


























