
trigger:
  - main  # Change this to match your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VAR_CLIENT_SECRET: $(CLIENT_SECRET)

steps:
  - checkout: self

  - task: TerraformInstaller@0
    displayName: "Install Terraform"
    inputs:
      terraformVersion: 'latest'

  - script: |
      terraform init \
        -backend=false
    displayName: "Terraform Init"

  - script: |
      terraform validate
    displayName: "Terraform Validate"

  - script: |
      terraform plan -out=tfplan
    displayName: "Terraform Plan"
    env:
      ARM_CLIENT_ID: "9decc6a2-0185-4bf0-829f-212b9b708ea1"
      ARM_CLIENT_SECRET: $(CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: "3e80dd4d-6d0e-48ec-a04b-c1401f2963bb"
      ARM_TENANT_ID: "79a50cb4-fa04-495b-9bd1-7860bc00fe6a"

  - script: |
      terraform apply -auto-approve tfplan
    displayName: "Terraform Apply"
    env:
      ARM_CLIENT_ID: "9decc6a2-0185-4bf0-829f-212b9b708ea1"
      ARM_CLIENT_SECRET: $(CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: "3e80dd4d-6d0e-48ec-a04b-c1401f2963bb"
      ARM_TENANT_ID: "79a50cb4-fa04-495b-9bd1-7860bc00fe6a"



















