trigger:
- main  # Change to your branch name as needed

jobs:
- job: TerraformPlan
  displayName: 'Run Terraform Plan'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: AzureCLI@2
    displayName: 'Authenticate with Azure'
    inputs:
      azureSubscription: 'azure-sc'  # Azure Service Connection Name (Azure DevOps)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Logging in to Azure with Service Principal"
        
        # Login with Service Principal using environment variables
        az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)

        # Set the Azure Subscription
        az account set --subscription $(subscriptionId)
        
        echo "Azure login successful"
  
  - task: TerraformInstaller@1
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: 'latest'

  - task: Bash@3
    displayName: 'Run Terraform Plan'
    inputs:
      targetType: 'inline'
      script: |
        terraform init
        terraform plan -out=tfplan

  - task: Bash@3
    displayName: 'Apply Terraform Plan'
    inputs:
      targetType: 'inline'
      script: |
        terraform apply -auto-approve tfplan






