trigger:
  - main  # Set this to match your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VAR_CLIENT_ID: $(CLIENT_ID)
  TF_VAR_CLIENT_SECRET: $(CLIENT_SECRET)
  TF_VAR_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
  TF_VAR_TENANT_ID: $(TENANT_ID)

steps:
  - checkout: self

  - task: TerraformInstaller@0
    displayName: "Install Terraform"
    inputs:
      terraformVersion: 'latest'

  - task: AzureCLI@2
    displayName: "Login to Azure"
    inputs:
      azureSubscription: "azure-sc"  # Service Connection Name
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az account show

  - script: |
      terraform init -backend=false
    displayName: "Terraform Init"

  - script: |
      terraform validate
    displayName: "Terraform Validate"

  - script: |
      terraform plan -out=tfplan
    displayName: "Terraform Plan"
    env:
      ARM_CLIENT_ID: $(CLIENT_ID)
      ARM_CLIENT_SECRET: $(CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(TENANT_ID)

  - script: |
      terraform apply -auto-approve tfplan
    displayName: "Terraform Apply"
    env:
      ARM_CLIENT_ID: $(CLIENT_ID)
      ARM_CLIENT_SECRET: $(CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(TENANT_ID)




















