trigger:
  branches:
    include:
      - main  # Trigger pipeline when pushing to the main branch

variables:
  - group: azure_credential  # Reference the variable group that contains the service principal credentials
  subscriptionId: $(subscriptionId)  # Reference the subscription ID from the variable group
  tenantId: $(tenantId)  # Reference the tenant ID from the variable group
  azureSubscription: 'azure-sc'  # Azure service connection name configured in Azure DevOps
  workingDirectory: $(System.DefaultWorkingDirectory)  # Directory for Terraform commands

jobs:
  - job: TerraformDeployment
    displayName: 'Deploy with Terraform'
    pool:
      vmImage: 'ubuntu-latest'  # Use Ubuntu for the build agent

    steps:
      # Azure CLI login using Service Principal from the variable group
      - task: AzureCLI@2
        inputs:
          azureSubscription: $(azureSubscription)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "Logging in with service principal..."
            az login --service-principal -u $(servicePrincipalId) --tenant $(tenantId) --password $(servicePrincipalKey)
            az account set --subscription $(subscriptionId)
            echo "Logged in successfully."

      # Terraform Init
      - task: AzureCLI@2
        inputs:
          azureSubscription: $(azureSubscription)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "Running Terraform init..."
            cd $(workingDirectory)
            terraform init

      # Terraform Plan
      - task: AzureCLI@2
        inputs:
          azureSubscription: $(azureSubscription)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "Running Terraform plan..."
            cd $(workingDirectory)
            terraform plan

      # Terraform Apply
      - task: AzureCLI@2
        inputs:
          azureSubscription: $(azureSubscription)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "Running Terraform apply..."
            cd $(workingDirectory)
            terraform apply -auto-approve



