trigger:
  - main  # Change this if your repo uses a different branch

variables:
  - group: azure_credential  # Ensures the variable group is linked

stages:
  - stage: Terraform_Deployment
    displayName: "Terraform Deployment"
    jobs:
      - job: Terraform
        displayName: "Run Terraform"
        pool:
          vmImage: "ubuntu-latest"

        steps:
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: "latest"

          - script: |
              echo "Debugging Environment Variables"
              echo "CLIENT_ID: $(CLIENT_ID)"
              echo "SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)"
              echo "TENANT_ID: $(TENANT_ID)"
            displayName: "Debug Environment Variables"

          - script: |
              terraform init
            displayName: "Terraform Init"
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)

          - script: |
              terraform plan -out=tfplan
            displayName: "Terraform Plan"
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)

          - script: |
              terraform apply -auto-approve tfplan
            displayName: "Terraform Apply"
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)






















