
trigger:
  branches:
    include:
      - main  # Ensure this matches your repo's branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Authenticate with Azure using the service connection
  - task: AzureCLI@2
    displayName: 'Azure Login'
    inputs:
      azureSubscription: 'azure-sc'  # Replace with your Azure Service Connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Login to Azure using Service Principal
        az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
        # Set the subscription for the Azure CLI session
        az account set --subscription $(ARM_SUBSCRIPTION_ID)

  # Install Terraform
  - task: Bash@3
    displayName: 'Install Terraform'
    inputs:
      targetType: 'inline'
      script: |
        sudo apt-get update
        sudo apt-get install -y gnupg software-properties-common
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update && sudo apt-get install terraform -y
        terraform --version

  # Initialize Terraform
  - task: Bash@3
    displayName: 'Terraform Init'
    inputs:
      targetType: 'inline'
      script: |
        export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
        export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
        export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
        export ARM_TENANT_ID=$(ARM_TENANT_ID)

        terraform init

  # Terraform Plan
  - task: Bash@3
    displayName: 'Terraform Plan'
    inputs:
      targetType: 'inline'
      script: |
        terraform plan -out=tfplan

  # Terraform Apply
  - task: Bash@3
    displayName: 'Terraform Apply'
    inputs:
      targetType: 'inline'
      script: |
        terraform apply -auto-approve tfplan
