trigger:
  - main  # Change this if your repo uses a different branch

variables:
  - group: azure_credential  # Ensures the variable group is linked

stages:
  - stage: Terraform_Deployment
    displayName: "Terraform Deployment"
    jobs:
      - job: Terraform
        displayName: "Run Terraform"
        pool:
          vmImage: "ubuntu-latest"

        steps:
          # Authenticate with Azure using the service connection
          - task: AzureCLI@2
            displayName: "Azure Authentication"
            inputs:
              azureSubscription: "azure-sc"  # Your Azure service connection name
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az account show
          
          # Debugging environment variables
          - script: |
              echo "Debugging Environment Variables"
              echo "CLIENT_ID: $(CLIENT_ID)"
              echo "SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)"
              echo "TENANT_ID: $(TENANT_ID)"
            displayName: "Debug Environment Variables"

          # Install Terraform
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: "latest"

          # Terraform Init Step
          - task: TerraformTaskV2@2
            displayName: "Terraform Init"
            inputs:
              provider: "azurerm"
              command: "init"
              backendServiceArm: "azure-sc"  # Use the service connection
              workingDirectory: "$(System.DefaultWorkingDirectory)"

          # Terraform Plan Step
          - task: TerraformTaskV2@2
            displayName: "Terraform Plan"
            inputs:
              provider: "azurerm"
              command: "plan"
              workingDirectory: "$(System.DefaultWorkingDirectory)"
              environmentServiceNameAzureRM: "azure-sc"

          # Terraform Apply Step
          - task: TerraformTaskV2@2
            displayName: "Terraform Apply"
            inputs:
              provider: "azurerm"
              command: "apply"
              commandOptions: "-auto-approve"
              workingDirectory: "$(System.DefaultWorkingDirectory)"
              environmentServiceNameAzureRM: "azure-sc"
























