trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  servicePrincipalId: $(servicePrincipalId)   # Ensure these are set in the pipeline's variables or pipeline secrets
  servicePrincipalKey: $(servicePrincipalKey)
  tenantId: $(tenantId)
  subscriptionId: $(subscriptionId)

steps:

# Step 1: Login to Azure using the Service Principal
- task: AzureCLI@2
  displayName: 'Azure CLI Login'
  inputs:
    azureSubscription: 'azure-sc'  # Azure Service Connection Name (Azure DevOps)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logging in to Azure with Service Principal"
      az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
      az account set --subscription $(subscriptionId)
      echo "Azure login successful"

# Step 2: Install Terraform
- task: TerraformInstaller@0
  displayName: 'Install Terraform'

# Step 3: Run Terraform Plan
- task: Bash@3
  displayName: 'Run Terraform Plan'
  inputs:
    targetType: 'inline'
    script: |
      echo "Running Terraform Plan"
      terraform init
      terraform plan







