trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Terraform
    jobs:
      - job: TerraformPlan
        steps:
          # Authenticate using Azure service connection
          - task: AzureCLI@2
            displayName: 'Authenticate with Azure'
            inputs:
              azureSubscription: 'azure-sc'  # Replace with your Azure service connection name
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Running Terraform init"
                rm -rf .terraform
                terraform init
                echo "Running Terraform plan"
                terraform plan
          
          # Run Terraform Plan
          - task: Bash@3
            displayName: 'Run Terraform Plan'
            inputs:
              targetType: 'inline'
              script: |
                terraform plan











