trigger:
  - main  # Change this if your repo uses a different branch

variables:
  - group: azure_credential  # Ensures the variable group is linked

stages:
  - stage: Terraform_Deployment
    displayName: "Terraform Deployment"
    jobs:
      - job: Terraform
        displayName: "Run Terraform"
        pool:
          vmImage: "ubuntu-latest"

        steps:
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: "latest"

          # Step to authenticate using Azure CLI
          - script: |
              echo "Authenticating with Azure using service principal credentials"
              az login --service-principal -u $(CLIENT_ID) -p $(CLIENT_SECRET) --tenant $(TENANT_ID)
            displayName: "Azure Authentication"
          
          # Debugging environment variables
          - script: |
              echo "Debugging Environment Variables"
              echo "CLIENT_ID: $(CLIENT_ID)"
              echo "SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)"
              echo "TENANT_ID: $(TENANT_ID)"
            displayName: "Debug Environment Variables"

          # Terraform Init Step
          - script: |
              terraform init
            displayName: "Terraform Init"
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)

          # Terraform Plan Step
          - script: |
              terraform plan -out=tfplan -input=false
            displayName: "Terraform Plan"
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)

          # Terraform Apply Step
          - script: |
              terraform apply -auto-approve tfplan
            displayName: "Terraform Apply"
            env:
              ARM_CLIENT_ID: $(CLIENT_ID)
              ARM_CLIENT_SECRET: $(CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)























