
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ARM_CLIENT_ID: $(servicePrincipalClientId)  # Set this to your Service Principal's client ID
  ARM_CLIENT_SECRET: $(servicePrincipalClientSecret)  # Set this to your Service Principal's client secret
  ARM_TENANT_ID: $(tenantId)  # Set this to your Tenant ID
  ARM_SUBSCRIPTION_ID: $(subscriptionId)  # Set this to your Subscription ID

jobs:
- job: Terraform
  steps:
    - task: AzureCLI@2
      displayName: 'Azure CLI login'
      inputs:
        azureSubscription: 'azure-sc'  # Name of the Azure service connection in DevOps
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
          az account set --subscription $ARM_SUBSCRIPTION_ID
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'
    - script: |
        terraform init
        terraform plan -out=tfplan
      displayName: 'Terraform Plan'


